### PR TITLE
Enable versioning on S3 buckets

### PR DESCRIPTION
**Pull request by JermilaPaulDhas**
This is to prevent subsequent ingests and transcodes from failing (https://trello.com/c/if3afY0L/321-automate-s3-versioning)

### CODE REVIEW

**Comment by jemrayfieldft** [comment]
Versioning not added to ansible/box/hosts.yml

**Comment by JermilaPaulDhas** [comment]
@jemrayfieldft That was intentional. Will we not incur a lot of cost if we add versioning on dev s3 buckets?

**Comment by jemrayfieldft** [comment]
Without versioning the workflows will fail.... so it has to be on

**Comment by JermilaPaulDhas** [comment]
Updated the PR

**Pull request merged**
