### PR TITLE
Cleanup while terminating a cluster

### PR DESCRIPTION
**Pull request by JermilaPaulDhas**
When terminating a cluster (EC2 instance in dev environment), the elb's, s3 buckets, the mounts and the database for the cluster does not get nuked.

This PR will cleanup the resources which is created when a cluster is spun up.

### CODE REVIEW

**Comment by jussi-ft** [comment]
Looks awesome. Great to addition to provisioner!

**Comment by jemrayfieldft** [comment]
Fails trying to drop database --->

TASK [drop database] ***********************************************************
fatal: [10.170.29.187]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to import docker-py - No module named docker. Try `pip install docker-py`"}

**Comment by JermilaPaulDhas** [comment]
@jemrayfieldft Did you run the install step of the deployment while you are tried to set up a cluster?
Docker is not installed on the server.

**Comment by jemrayfieldft** [comment]
Ill give it a try..

**Pull request merged**
