### PR TITLE
Restart docker containers on boot/failure

### PR DESCRIPTION
**Pull request by JermilaPaulDhas**
The development EC2 instances are stopped at 7 PM everyday by scroogebot. Restarting the instance the next day does not bring the containers back up.

This pull request would start the containers when the EC2 instance is booted/ on failure (in both dev and production instances).

### CODE REVIEW

**Comment by Dazzla** [comment]
* Nuked existing instance
* Added Konstructor key
* Ran ansible with BUILDOUT=build
* Ran ansible with default BUILDOUT
* Restarted annihilator (JIC)

```https://master-flex-darrendev.ft.com/
404```

Webservice seems to work:

```https://master-flex-darrendev.ft.com/api/metadataDefinitions:```

returns:
```{
  "totalCount": 0,
  "offset": 0,
  "limit": 100,
  "message": "No record(s) found."
}```

(Mio doesn't work here)

**Comment by jspc** [comment]
This is a flex bug that wants raising

**Comment by Dazzla** [comment]
Rebuilt as https://master-flex-qadev.ft.com/. GET request now returns:

```
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/enterprise/clusterId)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/shared/mysql/username)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/shared/mysql/host)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/shared/rabbitmq/password)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/enterprise/masterIPs)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/shared/rabbitmq/username)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/enterprise/mysql/database)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/shared/mysql/password)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/enterprise/jolokia/username)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/enterprise/jobIPs)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/enterprise/domainName)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/shared/mysql/username)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/shared/mysql/password)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/shared/mysql/host)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/enterprise/mysql/database)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/shared/mysql/host)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/shared/mysql/username)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/enterprise/jobIPs)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/enterprise/masterIPs)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/shared/mysql/password)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/enterprise/mysql/database)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/shared/smtp/host)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/shared/logstash/host)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/enterprise/domainName)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/enterprise/masterIPs)") Consul returned no data (does the path exist?)
master_1            | 2016/11/10 16:00:52 [WARN] ("key(flex/enterprise/jobIPs)") Consul returned no data (does the path exist?)
master_1            | the consul key "flex/shared/mysql/username" is missing, your configuration is incomplete.
```

**Comment by jspc** [comment]
Yeah, you have nothing in consul: https://consul-flex-qadev.ft.com/ui/#/dc1/kv/

**Comment by jemrayfieldft** [comment]
I get the following.

Which appears to be the same error darren saw and commented on ^^



[WARNING] 329/132757 (1) : [haproxy.main()] Cannot raise FD limit to 8209, limit is 4096.
[WARNING] 329/132757 (1) : [haproxy.main()] FD limit (4096) too low for maxconn=4096/maxsock=8209. Please raise 'ulimit-n' to 8209 or more to avoid any trouble.
[WARNING] 329/132757 (1) : Server project-creator/0244c8925d09 is DOWN, reason: Layer4 connection problem, info: "Connection refused", check duration: 0ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 329/132758 (1) : Server s3-club-7/0244c8925d09 is DOWN, reason: Layer4 connection problem, info: "Connection refused", check duration: 0ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
^C[root@ip-10-170-29-164 ~]docker-compose logs -f --tail 10 master
Attaching to root_master_1
master_1            | 2016-11-25 13:33:41,234 INFO  [com.hazelcast.core.LifecycleService] (hz.ShutdownThread) [10.170.29.164]:7801 [flex] [3.5.4] Address[10.170.29.164]:7801 is SHUTTING_DOWN
master_1            | 2016-11-25 13:33:41,266 INFO  [com.netflix.loadbalancer.DynamicServerListLoadBalancer] (Thread-85) Shutting down the Executor Pool for DynamicServerListLoadBalancer
master_1            | 2016-11-25 13:33:41,276 WARN  [com.hazelcast.instance.Node] (hz.ShutdownThread) [10.170.29.164]:7801 [flex] [3.5.4] Terminating forcefully...
master_1            | 2016-11-25 13:33:41,294 INFO  [com.hazelcast.instance.Node] (hz.ShutdownThread) [10.170.29.164]:7801 [flex] [3.5.4] Shutting down connection manager...
master_1            | 2016-11-25 13:33:41,296 INFO  [com.hazelcast.instance.Node] (hz.ShutdownThread) [10.170.29.164]:7801 [flex] [3.5.4] Shutting down node engine...
master_1            | 2016-11-25 13:33:41,303 INFO  [org.jboss.as] (MSC service thread 1-3) JBAS015950: JBoss EAP 6.3.3.GA (AS 7.4.3.Final-redhat-2) stopped in 15ms
master_1            | 2016-11-25 13:33:41,321 INFO  [com.hazelcast.instance.NodeExtension] (hz.ShutdownThread) [10.170.29.164]:7801 [flex] [3.5.4] Destroying node NodeExtension.
master_1            | 2016-11-25 13:33:41,325 INFO  [com.hazelcast.instance.Node] (hz.ShutdownThread) [10.170.29.164]:7801 [flex] [3.5.4] Hazelcast Shutdown is completed in 49 ms.
master_1            | 2016-11-25 13:33:41,325 INFO  [com.hazelcast.core.LifecycleService] (hz.ShutdownThread) [10.170.29.164]:7801 [flex] [3.5.4] Address[10.170.29.164]:7801 is SHUTDOWN
master_1            |
master_1            | 2016/11/25 13:33:51 [WARN] ("key(flex/enterprise/jobIPs)") Consul returned no data (does the path exist?)
master_1            | 2016/11/25 13:33:51 [WARN] ("key(flex/enterprise/jolokia/username)") Consul returned no data (does the path exist?)
master_1            | 2016/11/25 13:33:51 [WARN] ("key(flex/enterprise/clusterId)") Consul returned no data (does the path exist?)
master_1            | 2016/11/25 13:33:51 [WARN] ("key(flex/enterprise/masterIPs)") Consul returned no data (does the path exist?)
master_1            | 2016/11/25 13:33:51 [WARN] ("key(flex/shared/logstash/host)") Consul returned no data (does the path exist?)
master_1            | 2016/11/25 13:33:51 [WARN] ("key(flex/enterprise/jobIPs)") Consul returned no data (does the path exist?)
master_1            | 2016/11/25 13:33:51 [WARN] ("key(flex/enterprise/masterIPs)") Consul returned no data (does the path exist?)
master_1            | 2016/11/25 13:33:51 [WARN] ("key(flex/enterprise/jobIPs)") Consul returned no data (does the path exist?)
master_1            | 2016/11/25 13:33:51 [WARN] ("key(flex/enterprise/masterIPs)") Consul returned no data (does the path exist?)
master_1            | Applying DB migrations because you asked ($MIGRATE_DATABASE is set to "yes")
master_1            | migrating flex-db-infra-t-cluster.cpmz8xvttlgc.eu-west-1.rds.amazonaws.com
master_1            | Flyway 3.2.1 by Boxfuse
master_1            |
master_1            | Database: jdbc:mysql://flex-db-infra-t-cluster.cpmz8xvttlgc.eu-west-1.rds.amazonaws.com:3306/jemdev_master (MySQL 5.6)
master_1            | Validated 212 migrations (execution time 00:00.208s)
master_1            | Current version of schema `jemdev_master`: 1476100524
master_1            | WARNING: outOfOrder mode is active. Migration of schema `jemdev_master` may not be reproducible.
master_1            | Schema `jemdev_master` is up to date. No migration necessary.
master_1            | 2016-11-25 13:33:56,033 INFO  [org.jboss.as.connector.subsystems.datasources] (Controller Boot Thread) JBAS010404: Deploying non-JDBC-compliant driver class com.mysql.jdbc.Driver (version 5.1)
master_1            | 2016-11-25 13:33:56,165 INFO  [org.jboss.as.clustering.infinispan] (Controller Boot Thread) JBAS010280: Activating Infinispan subsystem.

**Pull request merged**
